// <auto-generated />
using System;
using LeadFinder.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadFinder.Web.Data.Migrations
{
    [DbContext(typeof(LeadFinderDbContext))]
    partial class LeadFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("LeadFinder.Web.Data.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("GooglePlacesApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("LeadFinder.Web.Data.BlockedPlaceEntity", b =>
                {
                    b.Property<string>("PlaceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PlaceId");

                    b.ToTable("BlockedPlaces");
                });

            modelBuilder.Entity("LeadFinder.Web.Data.LeadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryTone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsentGivenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstSearchRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWordPress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSearchRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePlatform")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StageChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserRatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("WebsiteReachable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebsiteUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("LeadFinder.Web.Data.SearchRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
